on:
  workflow_call:
    
jobs:

  draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    environment: Production
    outputs:
      release-id: ${{ steps.step-create-draft.outputs.release-id }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 18

    - name: Set Maven dependencies cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Create release draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: step-create-draft
      run: ./.github/workflows/scripts/create-draft-release.sh

  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    environment: Production
    needs: [draft-release]
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Approve release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID: ${{ needs.draft-release.outputs.release-id }}
        run: |
          . ./.github/workflows/scripts/github-functions.sh
          echo $(__approveAsset)
